/* sw.js for blanknotepad.com. Generated by tools/build_sw.py. Do not edit by hand.
 * Run "python3 tools/build_sw.py" after a change to any precached file.
 */
const VERSION = "2a25dd86acad";
const CACHE_NAME = "blanknotepad-" + VERSION;
const PRECACHE = [
  "/",
  "/about.html",
  "/privacy.html",
  "/terms.html",
  "/assets/js/register-sw.js",
  "/assets/js/nav.js",
  "/assets/css/styles.css",
  "/assets/js/markdown.js",
  "/assets/js/app.js"
];

self.addEventListener("install", (event) => {
  // Fetch every entry from the network. The "reload" cache mode keeps stale
  // bytes from the HTTP cache out of the precache.
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE.map((url) => new Request(url, { cache: "reload" }))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  // Delete every cache from an earlier deploy, then take control of open pages.
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys
          .filter((key) => key.startsWith("blanknotepad-") && key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  // Handle only GET requests to this origin. Return without respondWith for
  // every other request. The AdSense script and every other third-party
  // request go to the network directly. The worker never reads them and
  // never caches them.
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Cache first, then the network. The worker does not write network
  // responses into the cache. The precache is the whole offline set, and the
  // cache name changes on each deploy.
  event.respondWith(
    caches.match(request, { ignoreSearch: false }).then((hit) => {
      if (hit) return hit;
      if (request.mode !== "navigate") return fetch(request);
      return caches.match(url.pathname).then((byPath) => {
        if (byPath) return byPath;
        if (!url.pathname.endsWith("/")) return fetch(request);
        return caches.match(url.pathname + "index.html").then((byIndex) => byIndex || fetch(request));
      });
    })
  );
});
