#!/usr/bin/env python3
"""Generate sw.js for blanknotepad.com.

The precache list comes from sitemap.xml. The script reads each page and adds
every same-origin stylesheet and script that the page loads. The cache name is
"blanknotepad-" plus the first 12 hex characters of a hash over every precached
file. A change to any precached file gives a new cache name.

Usage:
    python3 tools/build_sw.py            Rewrite sw.js.
    python3 tools/build_sw.py --check    Exit 1 when sw.js is stale.

Python standard library only.
"""
import hashlib
import posixpath
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parent.parent
SITE = "blanknotepad"
SITEMAP = ROOT / "sitemap.xml"
OUT = ROOT / "sw.js"

SITEMAP_NS = "{http://www.sitemaps.org/schemas/sitemap/0.9}"
TAG_RE = re.compile(r"<(link|script)\b[^>]*>", re.IGNORECASE)
ATTR_RE = re.compile(r"""\b([a-zA-Z-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'>]+))""")

TEMPLATE = """/* sw.js for blanknotepad.com. Generated by tools/build_sw.py. Do not edit by hand.
 * Run "python3 tools/build_sw.py" after a change to any precached file.
 */
const VERSION = "%(version)s";
const CACHE_NAME = "%(site)s-" + VERSION;
const PRECACHE = [
%(precache)s
];

self.addEventListener("install", (event) => {
  // Fetch every entry from the network. The "reload" cache mode keeps stale
  // bytes from the HTTP cache out of the precache.
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE.map((url) => new Request(url, { cache: "reload" }))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  // Delete every cache from an earlier deploy, then take control of open pages.
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys
          .filter((key) => key.startsWith("%(site)s-") && key !== CACHE_NAME)
          .map((key) => caches.delete(key))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  // Handle only GET requests to this origin. Return without respondWith for
  // every other request. The AdSense script and every other third-party
  // request go to the network directly. The worker never reads them and
  // never caches them.
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Cache first, then the network. The worker does not write network
  // responses into the cache. The precache is the whole offline set, and the
  // cache name changes on each deploy.
  event.respondWith(
    caches.match(request, { ignoreSearch: false }).then((hit) => {
      if (hit) return hit;
      if (request.mode !== "navigate") return fetch(request);
      return caches.match(url.pathname).then((byPath) => {
        if (byPath) return byPath;
        if (!url.pathname.endsWith("/")) return fetch(request);
        return caches.match(url.pathname + "index.html").then((byIndex) => byIndex || fetch(request));
      });
    })
  );
});
"""


def page_urls():
    """Return the URL path of every page in sitemap.xml, in sitemap order."""
    tree = ET.parse(SITEMAP)
    paths = []
    for loc in tree.getroot().iter(SITEMAP_NS + "loc"):
        path = urlsplit(loc.text.strip()).path or "/"
        if path not in paths:
            paths.append(path)
    return paths


def file_for(url):
    """Map a request URL to the file that the server serves for it."""
    path = urlsplit(url).path
    if path.endswith("/"):
        path += "index.html"
    return ROOT / path.lstrip("/")


def attrs(tag):
    """Return the attributes of one HTML start tag as a dict."""
    found = {}
    for match in ATTR_RE.finditer(tag):
        name = match.group(1).lower()
        value = match.group(2) or match.group(3) or match.group(4) or ""
        found[name] = value
    return found


def same_origin(ref):
    """True for a path with no scheme and no host."""
    if not ref or ref.startswith("//") or ref.startswith("#"):
        return False
    return not urlsplit(ref).scheme and not urlsplit(ref).netloc


def asset_refs(page_url, html):
    """Return every same-origin stylesheet and script URL that the page loads."""
    refs = []
    for match in TAG_RE.finditer(html):
        tag = match.group(0)
        kind = match.group(1).lower()
        a = attrs(tag)
        if kind == "link":
            rels = a.get("rel", "").lower().split()
            ref = a.get("href") if "stylesheet" in rels else None
        else:
            ref = a.get("src")
        if not same_origin(ref):
            continue
        if not ref.startswith("/"):
            ref = posixpath.join(posixpath.dirname(urlsplit(page_url).path), ref)
        if ref not in refs:
            refs.append(ref)
    return refs


def precache_list():
    """Return the pages from the sitemap plus the assets that they load."""
    pages = page_urls()
    entries = list(pages)
    for page in pages:
        html = file_for(page).read_text(encoding="utf-8")
        for ref in asset_refs(page, html):
            if ref not in entries:
                entries.append(ref)
    return entries


def version_for(entries):
    """Hash the URL and the content of every entry. Return 12 hex characters."""
    digest = hashlib.sha256()
    for url in entries:
        digest.update(url.encode("utf-8"))
        digest.update(b"\0")
        digest.update(file_for(url).read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()[:12]


def render():
    entries = precache_list()
    missing = [url for url in entries if not file_for(url).is_file()]
    if missing:
        for url in missing:
            print("build_sw: no file for " + url, file=sys.stderr)
        sys.exit(2)
    precache = ",\n".join('  "%s"' % url for url in entries)
    return TEMPLATE % {"site": SITE, "version": version_for(entries), "precache": precache}, entries


def main(argv):
    text, entries = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != text:
            print("build_sw: sw.js is stale. Run: python3 tools/build_sw.py", file=sys.stderr)
            return 1
        print("build_sw: sw.js is current (%d precache entries)" % len(entries))
        return 0
    OUT.write_text(text, encoding="utf-8")
    print("build_sw: wrote sw.js (%d precache entries)" % len(entries))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
